name = "debthin"
main = "worker/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MIRROR_KV"
id = "e0d9c531f7f74676b1caf8991d59021d"          # replace after: wrangler kv:namespace create MIRROR_KV
preview_id = "8c526bce4cc44a3faa6ea22b3d18e23e"    # replace after: wrangler kv:namespace create MIRROR_KV --preview

[triggers]
crons = []  # Updates driven by GitHub Actions, not worker cron
